<a href="https://colab.research.google.com/github/Daywalker21/BTP_Y16/blob/master/Regression_W%20Nimish%20Sir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
from google.colab import files
uploaded = files.upload()

Saving regression data set Nimish  - Sheet1.csv to regression data set Nimish  - Sheet1 (3).csv


In [0]:
import io
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

dataframe = pd.read_csv(io.BytesIO(uploaded['regression data set Nimish  - Sheet1.csv']))
X = dataframe.iloc[:,0:4]
y = dataframe.iloc[:,-1] 

In [53]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
y_pred = lr.predict(X)

rmse = np.sqrt(mean_squared_error(y,y_pred))
r2 = r2_score(y,y_pred)

print(rmse)
print(r2)

lr.coef_

1.0839112704768892
0.8603845013531058


array([ 0.15832468,  0.13022321, -0.81640476, -0.06875714])

In [54]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(X)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)

rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)


print(rmse)
print(r2)

0.6774770386627
0.9454574637930605


In [55]:
model.coef_

array([ 0.00000000e+00,  2.01233821e-05, -7.89141587e-05,  3.60332854e-04,
        6.16246625e-06,  1.42876013e-03,  1.42645960e-02, -2.09221162e-02,
       -3.94023675e-03, -3.78787962e-03, -1.93839549e-02, -1.20891277e-03,
        5.76532566e-03,  9.80004214e-03,  3.08123312e-04])

In [56]:
polynomial_features.powers_

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [2, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 2, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 2]])

In [57]:
model.intercept_

12.658801741963323