<a href="https://colab.research.google.com/github/Daywalker21/BTP_Y16/blob/master/Regression_P%20Ashish%20Sir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
from google.colab import files
uploaded = files.upload()

Saving regression data set ashish - Sheet1.csv to regression data set ashish - Sheet1 (1).csv


In [0]:
import io
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

dataframe = pd.read_csv(io.BytesIO(uploaded['regression data set ashish - Sheet1.csv']))
X = dataframe.iloc[:,0:4]
y = dataframe.iloc[:,-2] 

In [33]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
y_pred = lr.predict(X)

rmse = np.sqrt(mean_squared_error(y,y_pred))
r2 = r2_score(y,y_pred)

print(rmse)
print(r2)

lr.coef_

0.2379897696565049
0.7001602791084103


array([-0.05625   ,  0.08744065, -0.16427198,  0.        ])

In [34]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(X)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)

rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)


print(rmse)
print(r2)

0.20002806104184517
0.7881861091428026


In [35]:
model.coef_

array([ 0.00000000e+00, -8.15323235e-01,  4.72846968e-02, -1.84423600e+00,
       -1.81596644e-01,  1.24344700e-02, -5.92105263e-03,  1.53846154e-02,
        7.50000000e-04,  6.62939947e-03, -2.27732794e-03, -7.89473684e-04,
        2.06472284e-02,  2.53846154e-02, -1.04193920e-03])

In [36]:
polynomial_features.powers_

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [2, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 2, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 2]])

In [37]:
model.intercept_

27.488506860013427