<a href="https://colab.research.google.com/github/Daywalker21/BTP_Y16/blob/master/Regression_H%20Ashish%20Sir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from google.colab import files
uploaded = files.upload()

Saving regression data set ashish - Sheet1.csv to regression data set ashish - Sheet1 (1).csv


In [0]:
import io
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

dataframe = pd.read_csv(io.BytesIO(uploaded['regression data set ashish - Sheet1.csv']))
X = dataframe.iloc[:,0:4]
y = dataframe.iloc[:,-3] 

In [29]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
y_pred = lr.predict(X)

rmse = np.sqrt(mean_squared_error(y,y_pred))
r2 = r2_score(y,y_pred)

print(rmse)
print(r2)

lr.coef_

0.20154789473754953
0.5505399502141995


array([-0.033125  ,  0.04150792, -0.139284  , -0.0135    ])

In [30]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(X)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)

rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)


print(rmse)
print(r2)

0.10496157615427083
0.8781023731545882


In [31]:
model.coef_

array([ 0.00000000e+00, -1.19858268e+00, -1.67141485e-01, -2.39260516e+00,
       -1.25375251e-01,  1.96979434e-02,  2.22039474e-03,  1.22596154e-02,
       -2.87500000e-03,  5.80464577e-03, -6.32591093e-04, -2.03947368e-03,
        8.39948675e-02,  7.88461538e-03,  2.20668375e-03])

In [32]:
polynomial_features.powers_

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [2, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 2, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 0, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 2]])

In [33]:
model.intercept_

34.56680347060689